/**
 * @brain/validation
 *
 * JSON Schema definitions and validators for Brain.
 * Provides AJV-based validation with TypeScript type safety.
 *
 * Usage:
 *   import {
 *     parseSearchArgs,
 *     validateSearchArgs,
 *     type SearchArgs
 *   } from '@brain/validation';
 */

export {
  // Types - Tool Args
  type ActiveProjectArgs,
  // Types - Session State
  type AgentInvocation,
  type AgentInvocationInput,
  type AgentInvocationOutput,
  type AgentType,
  type BootstrapContextArgs,
  type BrainConfig,
  type CompactionEntry,
  type ConfigGetArgs,
  type ConfigResetArgs,
  type ConfigSetArgs,
  type CreateProjectArgs,
  type Decision,
  type DecisionType,
  type DefaultsConfig,
  type DeleteProjectArgs,
  type EditProjectArgs,
  type GetProjectDetailsArgs,
  type GetWorkflowArgs,
  // Error retrieval
  getActiveProjectArgsErrors,
  getBootstrapContextArgsErrors,
  getBrainConfigErrors,
  getConfigGetArgsErrors,
  getConfigResetArgsErrors,
  getConfigSetArgsErrors,
  getCreateProjectArgsErrors,
  getDeleteProjectArgsErrors,
  getEditProjectArgsErrors,
  getGetProjectDetailsArgsErrors,
  getGetWorkflowArgsErrors,
  getListFeaturesByPriorityArgsErrors,
  getListProjectsArgsErrors,
  getListWorkflowsArgsErrors,
  getSearchArgsErrors,
  getSendWorkflowEventArgsErrors,
  getSessionArgsErrors,
  getSessionStateErrors,
  type Handoff,
  type InvocationStatus,
  // Type guards
  isAgentType,
  isSessionState,
  isWorkflowMode,
  type ListFeaturesByPriorityArgs,
  type ListProjectsArgs,
  type ListWorkflowsArgs,
  type LoggingConfig,
  type ModeHistoryEntry,
  type OrchestratorWorkflow,
  type ProjectConfig,
  // Parse functions (throw on error)
  parseActiveProjectArgs,
  parseBootstrapContextArgs,
  parseBrainConfig,
  parseConfigGetArgs,
  parseConfigResetArgs,
  parseConfigSetArgs,
  parseCreateProjectArgs,
  parseDeleteProjectArgs,
  parseEditProjectArgs,
  parseGetProjectDetailsArgs,
  parseGetWorkflowArgs,
  parseListFeaturesByPriorityArgs,
  parseListProjectsArgs,
  parseListWorkflowsArgs,
  parseSearchArgs,
  parseSendWorkflowEventArgs,
  parseSessionArgs,
  parseSessionState,
  type SearchArgs,
  type SendWorkflowEventArgs,
  type SessionArgs,
  type SessionState,
  type SyncConfig,
  safeParseSessionState,
  type ValidationError,
  type Verdict,
  type VerdictDecision,
  // Validators
  validateActiveProjectArgs,
  validateBootstrapContextArgs,
  validateBrainConfig,
  validateConfigGetArgs,
  validateConfigResetArgs,
  validateConfigSetArgs,
  validateCreateProjectArgs,
  validateDeleteProjectArgs,
  validateEditProjectArgs,
  validateGetProjectDetailsArgs,
  validateGetWorkflowArgs,
  validateListFeaturesByPriorityArgs,
  validateListProjectsArgs,
  validateListWorkflowsArgs,
  validateSearchArgs,
  validateSendWorkflowEventArgs,
  validateSessionArgs,
  validateSessionState,
  type WatcherConfig,
  type WorkflowMode,
  type WorkflowPhase,
} from "./validate";

// Naming pattern validators
export {
  DeprecatedPatterns,
  getMatchingPatterns,
  getPatternRegex,
  getPatternTypes,
  isValidNamingPattern,
  NamingPatterns,
  parseNamingPattern,
  validateNamingPattern,
  type NamingPatternResult,
  type PatternType,
} from "./naming-pattern";
