/**
 * @brain/validation
 *
 * JSON Schema definitions and validators for Brain.
 * Provides AJV-based validation with TypeScript type safety.
 *
 * Usage:
 *   import {
 *     parseSearchArgs,
 *     validateSearchArgs,
 *     type SearchArgs
 *   } from '@brain/validation';
 */

export {
  // Validators
  validateActiveProjectArgs,
  validateBootstrapContextArgs,
  validateBrainConfig,
  validateConfigGetArgs,
  validateConfigResetArgs,
  validateConfigSetArgs,
  validateCreateProjectArgs,
  validateDeleteProjectArgs,
  validateEditProjectArgs,
  validateGetProjectDetailsArgs,
  validateGetWorkflowArgs,
  validateListFeaturesByPriorityArgs,
  validateListProjectsArgs,
  validateListWorkflowsArgs,
  validateSearchArgs,
  validateSendWorkflowEventArgs,
  validateSessionArgs,
  validateSessionState,
  // Parse functions (throw on error)
  parseActiveProjectArgs,
  parseBootstrapContextArgs,
  parseBrainConfig,
  parseConfigGetArgs,
  parseConfigResetArgs,
  parseConfigSetArgs,
  parseCreateProjectArgs,
  parseDeleteProjectArgs,
  parseEditProjectArgs,
  parseGetProjectDetailsArgs,
  parseGetWorkflowArgs,
  parseListFeaturesByPriorityArgs,
  parseListProjectsArgs,
  parseListWorkflowsArgs,
  parseSearchArgs,
  parseSendWorkflowEventArgs,
  parseSessionArgs,
  parseSessionState,
  safeParseSessionState,
  // Error retrieval
  getActiveProjectArgsErrors,
  getBootstrapContextArgsErrors,
  getBrainConfigErrors,
  getConfigGetArgsErrors,
  getConfigResetArgsErrors,
  getConfigSetArgsErrors,
  getCreateProjectArgsErrors,
  getDeleteProjectArgsErrors,
  getEditProjectArgsErrors,
  getGetProjectDetailsArgsErrors,
  getGetWorkflowArgsErrors,
  getListFeaturesByPriorityArgsErrors,
  getListProjectsArgsErrors,
  getListWorkflowsArgsErrors,
  getSearchArgsErrors,
  getSendWorkflowEventArgsErrors,
  getSessionArgsErrors,
  getSessionStateErrors,
  // Type guards
  isAgentType,
  isWorkflowMode,
  isSessionState,
  // Types - Session State
  type AgentInvocation,
  type AgentInvocationInput,
  type AgentInvocationOutput,
  type AgentType,
  type CompactionEntry,
  type Decision,
  type DecisionType,
  type Handoff,
  type InvocationStatus,
  type ModeHistoryEntry,
  type OrchestratorWorkflow,
  type SessionState,
  type Verdict,
  type VerdictDecision,
  type WorkflowMode,
  type WorkflowPhase,
  // Types - Tool Args
  type ActiveProjectArgs,
  type BootstrapContextArgs,
  type BrainConfig,
  type ConfigGetArgs,
  type ConfigResetArgs,
  type ConfigSetArgs,
  type CreateProjectArgs,
  type DefaultsConfig,
  type DeleteProjectArgs,
  type EditProjectArgs,
  type GetProjectDetailsArgs,
  type GetWorkflowArgs,
  type ListFeaturesByPriorityArgs,
  type ListProjectsArgs,
  type ListWorkflowsArgs,
  type LoggingConfig,
  type ProjectConfig,
  type SearchArgs,
  type SendWorkflowEventArgs,
  type SessionArgs,
  type SyncConfig,
  type ValidationError,
  type WatcherConfig,
} from "./validate";
