version: 2

project_name: brain

before:
  hooks:
    - make embed

builds:
  - main: .
    dir: apps/tui
    binary: brain
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/peterkloss/brain-tui/cmd.Version={{.Version}}

archives:
  - format: binary
    name_template: "brain-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  use: github-native

release:
  github:
    owner: loriensleafs
    name: brain
