version: 2

project_name: brain

builds:
  - main: .
    dir: apps/tui
    binary: brain
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}

archives:
  - format: binary
    name_template: "brain-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  use: github-native

release:
  github:
    owner: peterkloss
    name: brain
